### ISSUE TITLE
Split job creation and job execution

### ISSUE THREAD

**Issue by juriansluiman** [Webador/SlmQueue#84]
There should be no need to push jobs with its instances only. This is done to keep the data integrity OK, but it also introduces the overhead of instantiating dependencies for jobs which aren't used at all. 

I know you can create proxies for those dependencies, but for new users this is quite difficult to understand. Alternatively, we can just force the job to be defined in the job plugin manager.

I also know this doesn't ensure the job is an instance of `JobInterface`, but if we log things properly (or: use exceptions properly) this can be overcome imho.

@basz @bakura10 thoughts?

**Comment by roelvanduijnhoven** [comment]
This has been bothering me for some time. I was about to raise an issue on it. 

Shouldn't be that hard as we simply broaden the API. 

Is everybody still :+1: on this one? If so: I'll take a stab at it!

**Comment by roelvanduijnhoven** [comment]
Actually I would also want to propose that one can also set metadata. If we do that one can simply add any job completely without having to instantiate anything. That would be ideal!

We can model that by adding an optional third parameter to the methods. We can also add this to the Controller plugin to match it.

**Comment by roelvanduijnhoven** [comment]
Sorry for the stream of updates!

I'd like to propose to create a value object `JobDescription` that is composed of three values: `name`, `payload` and `metadata`. It has thus enough information to instantiate any job. 

We now introduce a new method `pushByDescription` to the queue that accapts a single `JobDescription` value.

```php
$queue->pushByDescription(new JobDescription('send-text', ['text' => 'Hi from Holland'], ['metadata' => $someUniqueRequestUuid]));
```

What does this bring us? This way we can
* Create jobs without creating the actual job object and its dependencies without resorting to hacks.
* Create factory methods for jobs (additional gain of using value object).

----

That you can create factory methods is a big deal to me. In the following way I can logically group creation and execution. Though the factory method may obviously live anywhere as it is not part (and should not) of the interface.

```php
$queue->pushByDescription(SendTextJob::createDescription($phoneNumber, $text));
```

And the class:
```php
class Job extends AbstractJob
{
    public static function createDescription($phoneNumber, string $text) 
    {
        return new JobDescription(Job::class, [
            'to' => $phoneNumber,
            'body' => $text,
        ]);
    }

    protected $phoneGateway;

    public function __construct($phoneGateway) { .. }

    public function execute()
    {
        $content = $this->getContent();
        $this->phoneGateway->send($content['to'], $content['body']);
    }
}
```

Eager to hear what you tink @juriansluiman, @basz and @bakura10.

**Comment by basz** [comment]
I'm not so sure... What do you mean by factory methods exactly?

I understand the `new Job($dependency)` is a PITA when its dependencies are needed for execution only. 

possible solutions;
1. But in those cases a named constructor with some [reflection](http://php.net/manual/en/reflectionclass.newinstancewithoutconstructor.php) could solve that issue. 

```
class Job extends AbstractJob
{
    public static function createJobForPush($payload,$meta) : Job
    {
        $rc = new ReflectionClass(__CLASS__);
        $pushJob = $rc->newInstanceWithoutConstructor();
        $pushJob->setContent($payload);
        $pushJob->setMetdata($meta);

        return $pushJob;
    }
...
```

IMO you don't need an extra VO for this as the Job class itself can be it's own VO (sort of)...

2. You could also avoid using the constructor for execution dependencies and create setters on the job that its JobFactory uses. For push you can then simply do `$queue->push(new Job($payload, $meta));`.

3. Finally the controller plugin already can do a [push](https://github.com/juriansluiman/SlmQueue/blob/master/src/Controller/Plugin/QueuePlugin.php#L80) by job name.

Am I missing something?

**Comment by roelvanduijnhoven** [comment]
Thanks for the response; much appreciated!

So let me first reiterate what my problem is: there is now no sane way to communicate the creation of a job given some domain models. 

Having said that; let's look at solutions:

* __Optional dependencies__: IMO we are reusing / mixing the job instance for a task that is was not designed to do. It also really feels awkward / buggy having an instance that is not properly instantiated. I *do* use this in my code-base. I make the constructor private and have two static factory methods: `createJobDescription($params)` and `createRunnableJob($depA, $depB)`.
* __The controller plugin__: Here the mapping from domain model to payload / meta lives outside of the job. If you need to instantiate this job three times, you would need to duplicate the exact mapping three times. 

  What do I mean by that? Each call side (controllers, listeners) would have something along these lines for the same job. And these need to be copied / updated.

  ```php
  $this->queue(SendInvoiceReminder::class, ['invoiceId' => $invoice->getId(), 'to' => $invoice->getOwner()->getEmail()]);
  ```

* __JobDescription__ But I would rather have this. Here the mapping from domain model to payload (and optionally metadata!) is done in the job.

  ```php
  $this->queue(SendInvoiceReminder::class, ['invoice' => $invoice]);
  ```

  And my proposal was that you could do the following. This works because `createForJob` returns a `JobDescription`. This way we have type-checking; an extra guarantee.
  ```php
  $this->queue(SendInvoiceReminder::createJobForInvoice($invoice));  
  ```

  Note that the `createJobForInvoice` method is not part of any interface; and could very well live somewhere else! Thus one can do:

  ```
  $this->queue(new JobDescription(..));  
  ```

* __Reflection__: Your solution could work. We extend the interface (or add a new one) that has a static method. It fails however at communicating the mapping between domain logic and payload. But we could remodel that. That could look like:

  ```php
  class Job extends AbstractJob
  {
      public static function createJobFor(array $arguments) : Job
      {
           return []; // Returns the payload given the domain models given in `arguments`. 
      }
  ```

  Than we could use reflection indeed to call the static method. However: that *does* sound tricky. Not sure how that will play along with the service manager. Just like the router in V2 had some static factory methods :confused:.

Hope this makes some sense. I feel the `JobDescription` approach would be the best. It doesn't require any critical updates; while it does allow me to properly separate some concerns without resorting to hacks.

**Comment by basz** [comment]
I think I feel what your getting at... the reuse of the job class for 'descriptions' and 'execution' class does get in the way sometimes. so i don't mind of improving it such that domain logic would be better expressed.

Wouldn't an named constructor`MyJob::fromInvoice(Invoice $invoice)` work just as good? I worry introducing an additional Description class is not the correct way to go around instantiation without dependencies. We would need to add to the API and add some checks. `JobDescription` **is** as it stands the job  the description. Dependencies are only required (and even in some cases)  for execution time.

Note: `$this->queue(new JobDescription(..));` would actually be `$this->queue()->push(new JobDescription(..));` Therefore JobDescription must implement JobInterface, which feels a little weird and logic in `queue->push(...` must be added.

but i'm not sure... 

@prolic mind having a quick eye on this?

**Comment by roelvanduijnhoven** [comment]
> Wouldn't an named constructor `MyJob::fromInvoice(Invoice $invoice)` work just as good?

This is the __Optional dependencies__ solution. And indeed; the best way to do it now IMO. But it does require a partial / mixed job instance.

> Therefore JobDescription must implement JobInterface, which feels a little weird and logic in queue->push(... must be added.

Yes. I guess it would be better to introduce a new method `pushByDescription` or something similar. I'm actually not too fond of the `JobDescription` name myself.

Thanks for helping!

**Comment by prolic** [comment]
I read through the thread, and maybe I am totally wrong here, just my thoughts. Take it as advice or reject it as you wish.

The problem is coming from not following the `Single Responsibility` principle. You have a Job objects (which describes a job) and you want to have a possibility to execute this job. When you look at the real world, jobs are not executed by themselves, jobs are executed by workers. And this should do the `trick`.
Create instances of jobs in every way you wish, it's just a value object containing all the needed information. Once you push a job to the queue and is ready to be executed, the system will check if there is a worker for that given job, fetches it (thus injecting all the dependencies in the worker) and executes it.

Implementation is something like this:

```
interface Job
{
    public function name(): string;
    public function payload(): array;
    public function metadata(): array;
}

class SomeJob implements Job
{
    // do whatever you want to, just implement the interface
}

interface Worker
{
    public function execute(Job $job): void;
}

class SomeWorker implements Woker
{
    // do whatever you want here, inject all dependencies you need
}

$jobMap = [
    'some-job' => 'some-worker',
];

$queue = new Queue($backend, $workerPluginManager, $jobMap);
$queue->push(SomeJob::with(['some' => 'payload'], ['and' => 'metadata']));
```

**Comment by roelvanduijnhoven** [comment]
@prolic I see what you are aiming at. The solution solves the same set of problems I'd like to solve. But it does seem like a major BC compared with what SlmQueue is today. And given the activity on this repo I don't think that will be such a smart move.

My proposal instead tries to add an additional way to instantiate a job via a value object (`JobDescription`, but name could be different). In that way you can separate execution and instantiation already at this point; but without introducing breaking changes to the API. Much like the controller plugin partially did before. 

But yeah; maybe also not ideal. But it *does* solve issues present now.

Btw: the naming of Worker is confusing; as there already *is* a worker concept in the domain.

__Userland solution__
While typing this I think there already is a solution I can use to makes use of functionality already present. What if I introduce the following job:

```php
class JobProxy extends AbstractJob
{
    public function __construct($name, $content, $metadata = [])
    {
        $this->setMetadata(array_merge(
            $metadata,
            ['__name__' => $name]
        ));
        $this->setContent($content);
    }

    public function execute()
    {
        throw new \RuntimeException("JobCreator should not be executed itself.");
    }
}
```

And analoguely a `BinaryJobProxy` that simply implements `BinaryMessageInterface`.

And than when pushing I can for example do either one of the following:
```php
$this->queue->push(new ProxyJob(SendInvoice::class, ['invoiceId' => $invoice->getId()], []));
$this->queue->push(SendInvoice::createJob($invoice)); // Where createJob returns a `ProxyJob`
```

At the very least I think I am going to try this. 

Maybe *this* could land in master instead of some other hack? This requires *no* change to any of the adapter implementations.

**Comment by roelvanduijnhoven** [comment]
I'll update myself. The thing I dislike about the approach mentioned before is that it does not promote correct separation. And a other minor point is that the call-side needs to known whether the job is binary or not. I think we can improve on that. 

__Reflection__
We can use reflection to do so. But it will only work if we now for certain that each job name that is used maps directly to a valid class. At the moment this is only partially true I believe. But I find this a minor BC. 

But if we *do* choose to use reflection; maybe we can move in @basz's direction after all. What if we do the following. 

1. We create another method `QueueInterface::pushByName($class, $params, $metadata = [])`
2. The queue uses reflection to obtain whether it is a binary job. And also it checks whether the class implements the `BuildableJobInterface`. That interface describes a static `build(array $params)` method. 
3. If it does not implement the interface; it will throw an exception.
4. If it does implement it; it will go ahead and create the correct job. The build method will return a tuple (or value object) containing both payload and metadata. The final result will be:

    ```php
    function pushByName($jobClass, $params, $metadata = []) {
      // Check using reflection what interfaces $jobClass implements

      list($payload, $jobMetadata) = call_user_func($jobClass, 'build', $params);
      $metadata = array_merge($jobMetadata, $metadata);
      // Push a job of $jobClass with $payload and $metadata
    }
    ```

   Note that we merge the metadata. 

We could also choose to not throw an exception. But rather in that case the `$params` will be passed directly as `payload` :thinking:.

Anyway: what are thought on this @basz, @prolic, @bakura10?

**Comment by basz** [comment]
JobProxy seems a clever trick! But I think we are over complicating. Since there is no clear `Single Responsibility` as prolic has pointed out and such will not land without major BC and since a Job instance can be considered a VO for push onto the queue I don't see why the suggested would not work.

A named constructor on the job that uses reflection to skip calling the constructor and your done? All user land no changes needed! (I guess there's your `BuildableJobInterface`)
Or change your job and job factory such that they use a setter so you can instantiate without injecting dependencies.

That said;

1. pushByName suggests a service locator name, which isn't always true. I would suggest `pushFrom($class, $content, $metadata)`.

2a. We (c/sh?)ould have used metadata to mark content as binary as opposed to interfaces.

4. if BuildableJobInterface::build does not return instance of itself (as VO) what does it do?

**Comment by roelvanduijnhoven** [comment]
You are right. The trick you described earlier is a better way of doing things (vs what I suggested with `JobProxy`). I'll start using it at this point in time; and see how well it works outs. 

It would be nice to land such a feature in the repo itself. But all solutions have their limitations! 

I'll drop this for now; and simply start using the reflection method. Maybe I'll come up with something more clever while doing so. Or find other downsides.

**Comment by roelvanduijnhoven** [comment]
I have been using the trick you mentioned @basz for some time, and it is working excellent. I suggest we rewrite the docs such that we promote this style.

That being:
```php
final class EmailActivationJob extends AbstractJob
{
    public static function create(User $user): self
    {
        $rc = new \ReflectionClass(__CLASS__);

        /** @var static $job */
        $job = $rc->newInstanceWithoutConstructor();

        $job->setContent($user->getEmail());
        $job->setMetadata('userId', $user->getId()));

        return $job;
    }

    /**
     * @var SomeMailInterface
     */
    protected $mailer;

    public function __construct(SomeMailInterface $mailer)
    {
        $this->mailer = $mailer;
    }

    public function execute()
    {
        $this->mailer->mail(new SomeMail('Do not forget to activate!', $this->getContent()));
    }
}
```

That one can schedule from a controller as:
```php
$this->queue('default')->pushJob(EmailActivationJob::create($user));
```
